# arxivの学問領域の指定
subject: 'cat:cs.AI OR cat:cs.CE OR cat:cs.CV OR cat:cs.LG'
# subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 3
        explain: 3
        graph: 2
        deep learning: 1
        gradient boost: 1
        tabular: 3

# 通知の閾値
score_threshold: 0
